"""LLM-powered file description generator with SQLite cache.

Generates a 1-2 sentence natural language description for each file node.
Caches by (file_path, SHA-256 of file content) so re-runs are free for unchanged files.

For CLI users: requires OPENAI_API_KEY or --api-key flag.
For Claude Code skill users: descriptions are generated by the session Claude (no key needed).
"""

from __future__ import annotations

import hashlib
import sqlite3
from pathlib import Path
from typing import Callable

from rich.console import Console
from rich.progress import BarColumn, Progress, SpinnerColumn, TextColumn, TimeElapsedColumn

from .graph import Graph, Node

console = Console()

CACHE_DIR = Path.home() / ".prefxplain"
CACHE_DB = CACHE_DIR / "cache.db"

SYSTEM_PROMPT = """\
You are a senior software engineer writing concise documentation.
Given a source file's path, its top-level symbols, and a few lines of content,
write exactly 1-2 sentences describing what this file does and its role in the system.
Be specific about what the file provides to other parts of the codebase.
Do not repeat the filename. Do not start with "This file". Write in present tense.
"""

SYSTEM_PROMPT_DETAIL = """\
You are a senior software engineer writing thorough documentation.
Given a source file's path, its top-level symbols, and a few lines of content,
write a detailed paragraph (4-6 sentences) describing:
1. What this file does and its primary responsibility
2. Key functions/classes and what they provide
3. How it fits into the broader system architecture
4. Any notable patterns, dependencies, or design decisions
Be specific. Do not repeat the filename. Write in present tense.
"""

USER_PROMPT_TEMPLATE = """\
File: {file_path}
Language: {language}
Symbols: {symbols}

First {preview_lines} lines:
```
{preview}
```

Describe what this file does in {length_instruction}."""

_BRIEF_INSTRUCTION = "1-2 sentences"
_DETAIL_INSTRUCTION = "a detailed paragraph (4-6 sentences)"


def _init_cache() -> sqlite3.Connection:
    CACHE_DIR.mkdir(parents=True, exist_ok=True)
    conn = sqlite3.connect(str(CACHE_DB))
    conn.execute("""
        CREATE TABLE IF NOT EXISTS descriptions (
            file_path TEXT NOT NULL,
            content_hash TEXT NOT NULL,
            description TEXT NOT NULL,
            PRIMARY KEY (file_path, content_hash)
        )
    """)
    conn.commit()
    return conn


def _content_hash(file_path: Path) -> str:
    try:
        return hashlib.sha256(file_path.read_bytes()).hexdigest()
    except OSError:
        return ""


def _get_cached(conn: sqlite3.Connection, file_path: str, content_hash: str) -> str | None:
    row = conn.execute(
        "SELECT description FROM descriptions WHERE file_path = ? AND content_hash = ?",
        (file_path, content_hash),
    ).fetchone()
    return row[0] if row else None


def _set_cached(conn: sqlite3.Connection, file_path: str, content_hash: str, description: str) -> None:
    conn.execute(
        "INSERT OR REPLACE INTO descriptions (file_path, content_hash, description) VALUES (?, ?, ?)",
        (file_path, content_hash, description),
    )
    conn.commit()


def _file_preview(root: Path, node: Node, lines: int = 60) -> str:
    fpath = root / node.id
    try:
        if not fpath.resolve().is_relative_to(root.resolve()):
            return ""  # path traversal attempt
        text = fpath.read_text(encoding="utf-8", errors="ignore")
        return "\n".join(text.splitlines()[:lines])
    except OSError:
        return ""


def _make_prompt(node: Node, root: Path, detail: bool = False) -> str:
    symbols = ", ".join(s.name for s in node.symbols[:20]) or "none"
    preview_lines = 120 if detail else 60
    preview = _file_preview(root, node, lines=preview_lines)
    return USER_PROMPT_TEMPLATE.format(
        file_path=node.id,
        language=node.language,
        symbols=symbols,
        preview=preview,
        preview_lines=preview_lines,
        length_instruction=_DETAIL_INSTRUCTION if detail else _BRIEF_INSTRUCTION,
    )


def describe(
    graph: Graph,
    root: Path,
    api_key: str | None = None,
    api_base: str | None = None,
    model: str = "gpt-4o-mini",
    force: bool = False,
    detail: bool = False,
    progress_callback: Callable[[int, int], None] | None = None,
) -> Graph:
    """Fill in descriptions for all nodes that don't have one yet.

    Uses SQLite cache — only calls the LLM for files that changed since last run.

    Args:
        graph: Graph with nodes to describe.
        root: Repo root path (for reading file content).
        api_key: OpenAI-compatible API key. Falls back to OPENAI_API_KEY env var.
        api_base: Optional custom API base URL (for Ollama, Groq, etc.).
        model: LLM model name.
        force: Re-generate all descriptions, ignoring cache.
        detail: If True, generate paragraph-length descriptions instead of 1-2 sentences.
        progress_callback: Called with (current, total) for custom progress reporting.

    Returns:
        The same graph with descriptions filled in.
    """
    # Lazy import — openai is optional for Claude Code skill users
    try:
        from openai import OpenAI
    except ImportError:
        console.print("[yellow]openai package not installed. Run: pip install openai[/yellow]")
        console.print("[yellow]Skipping descriptions. Use --no-descriptions to suppress this warning.[/yellow]")
        return graph

    client_kwargs: dict = {}
    if api_key:
        client_kwargs["api_key"] = api_key
    if api_base:
        client_kwargs["base_url"] = api_base

    try:
        client = OpenAI(**client_kwargs)
    except Exception as e:
        console.print(f"[yellow]Could not initialize OpenAI client: {e}[/yellow]")
        console.print("[yellow]Skipping descriptions. Set OPENAI_API_KEY or use --no-descriptions.[/yellow]")
        return graph

    system_prompt = SYSTEM_PROMPT_DETAIL if detail else SYSTEM_PROMPT
    max_tokens = 400 if detail else 150

    conn = _init_cache()
    try:
        return _describe_with_conn(
            conn, graph, root, client, system_prompt, max_tokens, model, force, detail, progress_callback,
        )
    finally:
        conn.close()


def _describe_with_conn(
    conn: sqlite3.Connection,
    graph: Graph,
    root: Path,
    client: object,
    system_prompt: str,
    max_tokens: int,
    model: str,
    force: bool,
    detail: bool,
    progress_callback: Callable[[int, int], None] | None,
) -> Graph:
    nodes_to_describe = [n for n in graph.nodes if not n.description or force]
    total = len(nodes_to_describe)

    if total == 0:
        return graph

    with Progress(
        SpinnerColumn(),
        TextColumn("[progress.description]{task.description}"),
        BarColumn(),
        TextColumn("{task.completed}/{task.total}"),
        TimeElapsedColumn(),
        console=console,
    ) as progress:
        task = progress.add_task("Generating descriptions...", total=total)

        for i, node in enumerate(nodes_to_describe):
            fpath = root / node.id
            content_hash = _content_hash(fpath)

            # Check cache first (detail descriptions use a different key suffix)
            cache_key = f"{node.id}:detail" if detail else node.id
            if not force and content_hash:
                cached = _get_cached(conn, cache_key, content_hash)
                if cached:
                    node.description = cached
                    progress.advance(task)
                    if progress_callback:
                        progress_callback(i + 1, total)
                    continue

            # Call LLM
            try:
                response = client.chat.completions.create(
                    model=model,
                    messages=[
                        {"role": "system", "content": system_prompt},
                        {"role": "user", "content": _make_prompt(node, root, detail=detail)},
                    ],
                    max_tokens=max_tokens,
                    temperature=0.3,
                )
                content = response.choices[0].message.content if response.choices else None
                description = content.strip() if content else ""
            except Exception as e:
                console.print(f"[yellow]  Warning: LLM failed for {node.id}: {e}[/yellow]")
                description = ""

            node.description = description

            if content_hash and description:
                _set_cached(conn, cache_key, content_hash, description)

            progress.advance(task)
            if progress_callback:
                progress_callback(i + 1, total)

    return graph
